### ISSUE TITLE
example "evens ∪ odds = univ" fails

### ISSUE THREAD

**Issue by medovina** [avigad/mathematics_in_lean_source#177] opened 2024-02-04 07:30 UTC
I'm using Lean 4.5.0.

Section 4.1 "Sets" includes this example:

```
def evens : Set ℕ :=
  { n | Even n }

def odds : Set ℕ :=
  { n | ¬Even n }

example : evens ∪ odds = univ := by
  rw [evens, odds]
  ext n
  simp
  apply Classical.em
```

The last tactic (apply) fails:
```
tactic 'apply' failed, failed to unify
  ?p ∨ ¬?p
with
  Even n ∨ ¬Even n ↔ n ∈ univ
case h
univ : Set ℕ
n : ℕ
⊢ Even n ∨ ¬Even n ↔ n ∈ univ
```

**Comment by PatrickMassot** [comment] 2024-02-05 16:54
Thanks for your comment. I cannot reproduce this. You have probably broken something on your side.  Your "I'm using Lean 4.5.0." comment is very suspicious. You do not get to choose which version of Lean you use with Mathematics in Lean. It is specified in the lean-toolchain file that comes with the project. If you change it then you should expect lots of things to fail.

**Comment by PatrickMassot** [comment] 2024-02-05 16:59
Now that I have seen #175 I suspect this is the same issue: you are not following instructions and try to use the examples into an random context instead of playing with the code downloaded from https://github.com/leanprover-community/mathematics_in_lean.

**Comment by PatrickMassot** [comment] 2024-02-05 17:00
I am closing the issue in order to avoid confusing other readers, who could believe there is an actual issue. But feel free to ask more questions (asking them on Zulip is probably more convenient).

**Closed by PatrickMassot** 2024-02-05 17:00 UTC
